AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
    - '**/application.rb'
    - '**/*.rb'
  Exclude:
    # You could specify set of files or dirs while you want to be ignored by rubocop
    - 'vendor/**/*'
    - 'bin/*'
    - 'db/schema.rb'
    - 'Gemfile'
    - 'Gemfile.lock'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'config/add_vagrant_config.rb'
    - 'puppet/**/*'

Rails:
  Enabled: true

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'
    - 'spec/factories.rb'
    - 'spec/factories/**/*.rb'
    - 'Guardfile'
    - 'Vagrantfile'

Style/Documentation:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Rails/HttpPositionalArguments:
  Enabled: false # Can only be enabled once we're on Rails 5

Rails/SkipsModelValidations:
  Exclude:
    - 'db/migrate/**/*.rb'

Rails/OutputSafety:
  Enabled: false # Having weird errors with safe_join

Naming/FileName:
  Exclude:
    - 'Guardfile'
    - 'Vagrantfile'
    - 'Procfile'
    - 'puppet/Puppetfile'

RSpec/NestedGroups:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false

Lint/UnneededCopDisableDirective:
  Enabled: false # Used to gradually fix the rubocop rspec cops while not enabling it in the build
