// Generated by CoffeeScript 1.6.3
describe("AcceptedSessions", function() {
  return describe(".load", function() {
    return it("should hide all authors' bio", function() {
      setFixtures("<div id='sandbox'><div class='bio'></div></div>");
      expect($('.bio')).toBeVisible();
      new AcceptedSessions('#sandbox').load();
      return expect($('.bio')).toBeHidden();
    });
  });
});
